language: python
python:
- '2.7'
install: pip install requests
deploy:
  provider: s3
  access_key_id: AKIAIUJWXAA6UNQXBQNA
  secret_access_key: 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
  bucket: s3.johanwiren.se
  region: eu-west-1
  endpoint: s3.johanwiren.se.s3-website-eu-west-1.amazonaws.com
  skip_cleanup: true
  local-dir: dist
  upload-dir: packages/johanwiren/mysl
script: python setup.py sdist
