language: python
python:
- '2.7'
install: pip install requests
deploy:
  provider: s3
  access_key_id: AKIAIUJWXAA6UNQXBQNA
  secret_access_key:
    secure: Am+GVzGDH5HdYu+eiP8UcaX1e4qw0jn8CTcBNtszAp7aNDyihm/Xtl2bCZufgZlGcQHH0EolZVMl3ROqFLE3RHffvOGMmxYtbwaDHi1z0xOi2ZuvhQ/A0kp4tlOAio0VhVaowLgwq6uU2JBy3jgPiRtaMJUf9Ll6XCWuR7IoYTw=
  bucket: s3.johanwiren.se
  region: eu-west-1
  skip_cleanup: true
  local-dir: dist
  upload-dir: packages/johanwiren/mysl
script: python setup.py sdist
